# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtCore import Qt
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtOpenGLWidgets import QOpenGLWidget
from voice_assistant_visualizer.widget import AudioVisualizerWidget  
from .resources_rc import *
from .logger import log

log.info("App_ui initialized")
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1397, 1062)
        MainWindow.setStyleSheet("background-color: rgb(35, 39, 46)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.voiceChatLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.voiceChatLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.voiceChatLabel.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        MainWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        self.voiceChatLabel.setFont(font)
        self.voiceChatLabel.setStyleSheet("color:rgb(127, 132, 142)")
        self.voiceChatLabel.setObjectName("voiceChatLabel")
        self.verticalLayout_2.addWidget(self.voiceChatLabel)
        self.audioVisualizer = AudioVisualizerWidget(parent=self.centralwidget)
        self.audioVisualizer.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.audioVisualizer.setMinimumSize(QtCore.QSize(512, 512))
        self.audioVisualizer.setObjectName("audioVisualizer")
        self.verticalLayout_2.addWidget(self.audioVisualizer)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.volumeSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.volumeSlider.setMinimumSize(QtCore.QSize(120, 20))
        self.volumeSlider.setMaximumSize(QtCore.QSize(128, 32))
        self.volumeSlider.setStyleSheet("QSlider {\n"
"    min-height: 20px;\n"
"    min-width: 120px;\n"
"}\n"
"\n"
"/* --- Groove / Bahn --- */\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background: #E6EBF1;\n"
"    border-radius: 3px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 6px;\n"
"    background: #E6EBF1;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* --- Gefüllter Teil (links/unten vom Griff) --- */\n"
"QSlider::sub-page:horizontal {\n"
"    background: #2E86C1;\n"
"    border-radius: 3px;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #2E86C1;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* Hover-Effekt */\n"
"QSlider::sub-page:horizontal:hover,\n"
"QSlider::sub-page:vertical:hover {\n"
"    background: #5DADE2;\n"
"}\n"
"\n"
"/* --- Restlicher Teil (rechts/oben vom Griff) --- */\n"
"QSlider::add-page:horizontal,\n"
"QSlider::add-page:vertical {\n"
"    background: #DCE3EA;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* --- Griff / Handle --- */\n"
"QSlider::handle:horizontal {\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #21618C;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -5px 0px;           /* Nur vertikal ausrichten, KEIN horizontaler Abstand! */\n"
"    border-radius: 8px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #FFFFFF;\n"
"    border: 2px solid #21618C;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: 0px -5px;           /* Nur horizontal ausrichten, KEIN vertikaler Abstand! */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Hover & Pressed */\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover {\n"
"    background: #F5FAFF;\n"
"    border-color: #2E86C1;\n"
"}\n"
"QSlider::handle:horizontal:pressed,\n"
"QSlider::handle:vertical:pressed {\n"
"    background: #2E86C1;\n"
"    border-color: #1B4F72;\n"
"}\n"
"")
        self.volumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.volumeSlider.setValue(50)
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        self.volumeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeButton.setMaximumSize(QtCore.QSize(75, 32))
        self.volumeButton.setStyleSheet("QPushButton {\n"
"    background-color: #B03A2E; \n"
"    color: white;\n"
"    border: 1px solid #873B32;\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CD6155;   \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #2E86C1;  \n"
"    border: 1px solid #21618C;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"    background-color: #5DADE2;   \n"
"}\n"
"")
        self.volumeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/volume-x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/resources/volume-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.volumeButton.setIcon(icon)
        self.volumeButton.setCheckable(True)
        self.volumeButton.setChecked(True)
        self.volumeButton.setObjectName("volumeButton")
        self.horizontalLayout_2.addWidget(self.volumeButton)
        self.micButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.micButton.setMaximumSize(QtCore.QSize(75, 32))
        self.micButton.setStyleSheet("QPushButton {\n"
"    background-color: #B03A2E; \n"
"    color: white;\n"
"    border: 1px solid #873B32;\n"
"    padding: 8px 16px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #CD6155;   \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #2E86C1;  \n"
"    border: 1px solid #21618C;\n"
"}\n"
"\n"
"QPushButton:checked:hover {\n"
"    background-color: #5DADE2;   \n"
"}\n"
"")
        self.micButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/mic-off.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/resources/mic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.micButton.setIcon(icon1)
        self.micButton.setCheckable(True)
        self.micButton.setChecked(True)
        self.micButton.setObjectName("micButton")
        self.horizontalLayout_2.addWidget(self.micButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        spacerItem2 = QtWidgets.QSpacerItem(538, 16, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 32))
        self.frame.setStyleSheet("QPushButton {\n"
"    color: rgb(127, 132, 142);\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(161, 167, 180)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.settingsButton = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        self.settingsButton.setFont(font)
        self.settingsButton.setCheckable(False)
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout_3.addWidget(self.settingsButton)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.chatHistory = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.chatHistory.setStyleSheet("QScrollArea {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"   }\n"
"   QScrollArea > QWidget > QWidget {\n"
"    background-color: transparent;\n"
"   }\n"
"   QScrollBar {\n"
"    background-color: transparent;\n"
"   }")
        self.chatHistory.setWidgetResizable(True)
        self.chatHistory.setObjectName("chatHistory")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chatLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.chatLayout.setSpacing(8)
        self.chatLayout.setObjectName("chatLayout")
        self.chatHistory.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.chatHistory)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.messageInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.messageInput.setMinimumSize(QtCore.QSize(0, 32))
        self.messageInput.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.messageInput.setObjectName("messageInput")
        self.horizontalLayout.addWidget(self.messageInput)
        self.sendButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sendButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border-radius: 4px;\n"
"    background-color: #2E86C1;  \n"
"    border: 1px solid #21618C;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3E5C76;  \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #2E86C1;  \n"
"    border: 1px solid #21618C;\n"
"}\n"
"\n"
"")
        self.sendButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sendButton.setIcon(icon2)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.clearContextButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearContextButton.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 8px 12px;\n"
"    border-radius: 4px;\n"
"    background-color: #2E86C1;  \n"
"    border: 1px solid #21618C;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5DADE2;   \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3E5C76;  \n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #2E86C1;  \n"
"    border: 1px solid #21618C;\n"
"}\n"
"\n"
"")
        self.clearContextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clearContextButton.setIcon(icon3)
        self.clearContextButton.setObjectName("clearContextButton")
        self.horizontalLayout.addWidget(self.clearContextButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AXEL-MKI"))  # Fenster-Titel
        self.voiceChatLabel.setText(_translate("MainWindow", "AXEL-MKI"))  # VoiceChat-Label ändern
        self.settingsButton.setText(_translate("MainWindow", "Settings  "))

